export const ST_EVENT_TYPES = {
  APP_INITIALIZED: 'app_initialized', // public/scripts/events.js:4
  APP_READY: 'app_ready', // public/scripts/events.js:5
  EXTRAS_CONNECTED: 'extras_connected', // public/scripts/events.js:6
  MESSAGE_SWIPED: 'message_swiped', // public/scripts/events.js:7
  MESSAGE_SENT: 'message_sent', // public/scripts/events.js:8
  MESSAGE_RECEIVED: 'message_received', // public/scripts/events.js:9
  MESSAGE_EDITED: 'message_edited', // public/scripts/events.js:10
  MESSAGE_DELETED: 'message_deleted', // public/scripts/events.js:11
  MESSAGE_UPDATED: 'message_updated', // public/scripts/events.js:12
  MESSAGE_FILE_EMBEDDED: 'message_file_embedded', // public/scripts/events.js:13
  MESSAGE_REASONING_EDITED: 'message_reasoning_edited', // public/scripts/events.js:14
  MESSAGE_REASONING_DELETED: 'message_reasoning_deleted', // public/scripts/events.js:15
  MESSAGE_SWIPE_DELETED: 'message_swipe_deleted', // public/scripts/events.js:16
  MORE_MESSAGES_LOADED: 'more_messages_loaded', // public/scripts/events.js:17
  IMPERSONATE_READY: 'impersonate_ready', // public/scripts/events.js:18
  CHAT_CHANGED: 'chat_id_changed', // public/scripts/events.js:19
  CHAT_LOADED: 'chatLoaded', // public/scripts/events.js:21
  GENERATION_AFTER_COMMANDS: 'GENERATION_AFTER_COMMANDS', // public/scripts/events.js:22
  GENERATION_STARTED: 'generation_started', // public/scripts/events.js:23
  GENERATION_STOPPED: 'generation_stopped', // public/scripts/events.js:24
  GENERATION_ENDED: 'generation_ended', // public/scripts/events.js:25
  SD_PROMPT_PROCESSING: 'sd_prompt_processing', // public/scripts/events.js:26
  EXTENSIONS_FIRST_LOAD: 'extensions_first_load', // public/scripts/events.js:27
  EXTENSION_SETTINGS_LOADED: 'extension_settings_loaded', // public/scripts/events.js:28
  SETTINGS_LOADED: 'settings_loaded', // public/scripts/events.js:29
  SETTINGS_UPDATED: 'settings_updated', // public/scripts/events.js:30
  GROUP_UPDATED: 'group_updated', // public/scripts/events.js:31
  MOVABLE_PANELS_RESET: 'movable_panels_reset', // public/scripts/events.js:32
  SETTINGS_LOADED_BEFORE: 'settings_loaded_before', // public/scripts/events.js:33
  SETTINGS_LOADED_AFTER: 'settings_loaded_after', // public/scripts/events.js:34
  CHATCOMPLETION_SOURCE_CHANGED: 'chatcompletion_source_changed', // public/scripts/events.js:35
  CHATCOMPLETION_MODEL_CHANGED: 'chatcompletion_model_changed', // public/scripts/events.js:36
  OAI_PRESET_CHANGED_BEFORE: 'oai_preset_changed_before', // public/scripts/events.js:37
  OAI_PRESET_CHANGED_AFTER: 'oai_preset_changed_after', // public/scripts/events.js:38
  OAI_PRESET_EXPORT_READY: 'oai_preset_export_ready', // public/scripts/events.js:39
  OAI_PRESET_IMPORT_READY: 'oai_preset_import_ready', // public/scripts/events.js:40
  WORLDINFO_SETTINGS_UPDATED: 'worldinfo_settings_updated', // public/scripts/events.js:41
  WORLDINFO_UPDATED: 'worldinfo_updated', // public/scripts/events.js:42
  CHARACTER_EDITOR_OPENED: 'character_editor_opened', // public/scripts/events.js:43
  CHARACTER_EDITED: 'character_edited', // public/scripts/events.js:44
  CHARACTER_PAGE_LOADED: 'character_page_loaded', // public/scripts/events.js:45
  CHARACTER_GROUP_OVERLAY_STATE_CHANGE_BEFORE: 'character_group_overlay_state_change_before', // public/scripts/events.js:46
  CHARACTER_GROUP_OVERLAY_STATE_CHANGE_AFTER: 'character_group_overlay_state_change_after', // public/scripts/events.js:47
  USER_MESSAGE_RENDERED: 'user_message_rendered', // public/scripts/events.js:48
  CHARACTER_MESSAGE_RENDERED: 'character_message_rendered', // public/scripts/events.js:49
  FORCE_SET_BACKGROUND: 'force_set_background', // public/scripts/events.js:50
  CHAT_DELETED: 'chat_deleted', // public/scripts/events.js:51
  CHAT_CREATED: 'chat_created', // public/scripts/events.js:52
  CHAT_RENAMED: 'chat_renamed', // public/scripts/events.js:53
  GROUP_CHAT_DELETED: 'group_chat_deleted', // public/scripts/events.js:54
  GROUP_CHAT_CREATED: 'group_chat_created', // public/scripts/events.js:55
  GENERATE_BEFORE_COMBINE_PROMPTS: 'generate_before_combine_prompts', // public/scripts/events.js:56
  GENERATE_AFTER_COMBINE_PROMPTS: 'generate_after_combine_prompts', // public/scripts/events.js:57
  GENERATE_AFTER_DATA: 'generate_after_data', // public/scripts/events.js:58
  GROUP_MEMBER_DRAFTED: 'group_member_drafted', // public/scripts/events.js:59
  GROUP_WRAPPER_STARTED: 'group_wrapper_started', // public/scripts/events.js:60
  GROUP_WRAPPER_FINISHED: 'group_wrapper_finished', // public/scripts/events.js:61
  WORLD_INFO_ACTIVATED: 'world_info_activated', // public/scripts/events.js:62
  TEXT_COMPLETION_SETTINGS_READY: 'text_completion_settings_ready', // public/scripts/events.js:63
  CHAT_COMPLETION_SETTINGS_READY: 'chat_completion_settings_ready', // public/scripts/events.js:64
  CHAT_COMPLETION_PROMPT_READY: 'chat_completion_prompt_ready', // public/scripts/events.js:65
  CHARACTER_FIRST_MESSAGE_SELECTED: 'character_first_message_selected', // public/scripts/events.js:66
  CHARACTER_DELETED: 'characterDeleted', // public/scripts/events.js:68
  CHARACTER_DUPLICATED: 'character_duplicated', // public/scripts/events.js:69
  CHARACTER_RENAMED: 'character_renamed', // public/scripts/events.js:70
  CHARACTER_RENAMED_IN_PAST_CHAT: 'character_renamed_in_past_chat', // public/scripts/events.js:71
  SMOOTH_STREAM_TOKEN_RECEIVED: 'stream_token_received', // public/scripts/events.js:73
  STREAM_TOKEN_RECEIVED: 'stream_token_received', // public/scripts/events.js:74
  STREAM_REASONING_DONE: 'stream_reasoning_done', // public/scripts/events.js:75
  FILE_ATTACHMENT_DELETED: 'file_attachment_deleted', // public/scripts/events.js:76
  WORLDINFO_FORCE_ACTIVATE: 'worldinfo_force_activate', // public/scripts/events.js:77
  OPEN_CHARACTER_LIBRARY: 'open_character_library', // public/scripts/events.js:78
  ONLINE_STATUS_CHANGED: 'online_status_changed', // public/scripts/events.js:79
  IMAGE_SWIPED: 'image_swiped', // public/scripts/events.js:80
  CONNECTION_PROFILE_LOADED: 'connection_profile_loaded', // public/scripts/events.js:81
  CONNECTION_PROFILE_CREATED: 'connection_profile_created', // public/scripts/events.js:82
  CONNECTION_PROFILE_DELETED: 'connection_profile_deleted', // public/scripts/events.js:83
  CONNECTION_PROFILE_UPDATED: 'connection_profile_updated', // public/scripts/events.js:84
  TOOL_CALLS_PERFORMED: 'tool_calls_performed', // public/scripts/events.js:85
  TOOL_CALLS_RENDERED: 'tool_calls_rendered', // public/scripts/events.js:86
  CHARACTER_MANAGEMENT_DROPDOWN: 'charManagementDropdown', // public/scripts/events.js:87
  SECRET_WRITTEN: 'secret_written', // public/scripts/events.js:88
  SECRET_DELETED: 'secret_deleted', // public/scripts/events.js:89
  SECRET_ROTATED: 'secret_rotated', // public/scripts/events.js:90
  SECRET_EDITED: 'secret_edited', // public/scripts/events.js:91
  PRESET_CHANGED: 'preset_changed', // public/scripts/events.js:92
  PRESET_DELETED: 'preset_deleted', // public/scripts/events.js:93
  PRESET_RENAMED: 'preset_renamed', // public/scripts/events.js:94
  PRESET_RENAMED_BEFORE: 'preset_renamed_before', // public/scripts/events.js:95
  MAIN_API_CHANGED: 'main_api_changed', // public/scripts/events.js:96
  WORLDINFO_ENTRIES_LOADED: 'worldinfo_entries_loaded', // public/scripts/events.js:97
  WORLDINFO_SCAN_DONE: 'worldinfo_scan_done', // public/scripts/events.js:98
  MEDIA_ATTACHMENT_DELETED: 'media_attachment_deleted', // public/scripts/events.js:99
  PERSONA_CHANGED: 'persona_changed', // public/scripts/events.js:100
  PERSONA_CREATED: 'persona_created', // public/scripts/events.js:101
  PERSONA_UPDATED: 'persona_updated', // public/scripts/events.js:102
  PERSONA_RENAMED: 'persona_renamed', // public/scripts/events.js:103
  PERSONA_DELETED: 'persona_deleted', // public/scripts/events.js:104
  TTS_JOB_STARTED: 'tts_job_started', // public/scripts/events.js:105
  TTS_AUDIO_READY: 'tts_audio_ready', // public/scripts/events.js:106
  TTS_JOB_COMPLETE: 'tts_job_complete', // public/scripts/events.js:107
  ITEMIZED_PROMPTS_LOADED: 'itemized_prompts_loaded', // public/scripts/events.js:108
  ITEMIZED_PROMPTS_SAVED: 'itemized_prompts_saved', // public/scripts/events.js:109
  ITEMIZED_PROMPTS_DELETED: 'itemized_prompts_deleted', // public/scripts/events.js:110
} as const;

export type STEventTypeName = keyof typeof ST_EVENT_TYPES;
export type STEventType = (typeof ST_EVENT_TYPES)[STEventTypeName];
